# Generated by Django 6.0.5 on 2026-05-15 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(30)])),
                ('country', models.CharField(max_length=100)),
                ('faith_background', models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('islam', 'Islam'), ('christianity', 'Christianity'), ('judaism', 'Judaism'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('other', 'Other')], default='', max_length=100)),
                ('education_level', models.CharField(choices=[('high_school', 'High School Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD / Doctorate'), ('other', 'Other')], max_length=50)),
                ('ngo_experience', models.TextField(help_text='Describe any NGO or volunteer experience')),
                ('why_join_essay', models.TextField(help_text='Why do you want to join? (~200 words)')),
                ('preferred_location', models.CharField(blank=True, choices=[('lebanon', 'Lebanon'), ('jordan', 'Jordan'), ('tunisia', 'Tunisia'), ('albania', 'Albania'), ('indonesia', 'Indonesia'), ('other', 'Other')], max_length=50)),
                ('cv', models.FileField(help_text='PDF or Word document, max 5MB', upload_to='cvs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('synced_to_sheets', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
