services:
  - type: web
    name: climaticpeace
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn climaticpeace.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
